services:

  core.manager:
      class: CoreBundle\Utils\CoreManager
      arguments: ['@doctrine.orm.default_entity_manager']

#    core.example:
#        class: CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
