variables:
  COMPOSER_DISABLE_XDEBUG_WARN: "1"

cache:
 paths:
   - vendor/

before_script:
# Install mysql driver
- docker-php-ext-enable gd zip pdo_mysql xdebug intl

# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- mv app/config/parameters.gitlab.yml app/config/parameters.yml.dist
- ping -c 3 mysql
- php -v
- composer install
- php bin/console doctrine:schema:create
- php bin/console doctrine:fixtures:load --no-interaction

# remove cache folders
- rm -r var/cache/

#configuring LexitJWTAuth
- rm -r var/jwt; mkdir var/jwt
- openssl genrsa -out var/jwt/private.pem -passout pass:pleaseChangeMe -aes256 4096
- openssl rsa -passin pass:pleaseChangeMe -pubout -in var/jwt/private.pem -out var/jwt/public.pem


services:
- mysql:latest

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: symfony
  MYSQL_ROOT_PASSWORD: password

test70:
  stage: test
  image: tetraweb/php:7.0
  script:
    - ./vendor/bin/phpunit --verbose --tap

pages:
  stage: deploy
  image: tetraweb/php:7.0
  only:
    - master
  script:
    - ./vendor/bin/phpmetrics --report-html=build/phpmetrics/index.html src/
#    - ./vendor/bin/phpunit --coverage-html build/phpunit/
  artifacts:
    paths:
    - public