variables:
  COMPOSER_DISABLE_XDEBUG_WARN: "1"

cache:
 paths:
   - vendor/

test70:
  stage: test
  image: melkorm/php-docker:7.0
  before_script:
    - composer install
  script:
    - ./vendor/bin/phpunit

pages:
  stage: deploy
  image: melkorm/php-docker:7.0
  before_script:
    - composer install
  only:
    - master
  script:
    - ./vendor/bin/phpmetrics --report-html=build/phpmetrics/index.html app/
    - ./vendor/bin/phpunit --coverage-html build/phpunit/
    - rm -rf public/
    - cp -r build/ public/
  artifacts:
    paths:
    - public