<?php

namespace CoreBundle\Entity\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{


    public function search(array $search = [])
    {
        $query = $this->createQueryBuilder('e')->select('e');

        if (!empty($search['query'])) {
            $query->orWhere('e.name like :query')
                ->orWhere('e.description like :query')
                ->setParameter('query', '%' . $search['query'] . '%');
        }

        if (isset($search['orderBy']) && is_array($search['orderBy'])) {
            foreach ($search['orderBy'] as $orderBy) {
                if (preg_match('/^(id|name|createdAt|updatedAt) (ASC|DESC)/', $orderBy)) {
                    list($column, $dir) = explode(' ', $orderBy);
                    $query->addOrderBy('e.' . $column, $dir);
                }
            }
        }

        $paginator = new Paginator($query->getQuery());

        $paginator->getQuery()
            ->setFirstResult($search['limit'] * ($search['page'] - 1))
            ->setMaxResults($search['limit']);

        return [
            'data' => $paginator->getQuery()->getResult(),
            'pagesCount' => (int) ceil($paginator->count() / $paginator->getQuery()->getMaxResults()),
            'totalItems' => (int) $paginator->count(),
        ];
    }

}
