<?php

namespace CoreBundle\Entity\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function search(array $query = [])
    {

        if(!isset($search['page']) || $search['page'] <= 0) {
            $page = 1;
        } else {
            $page = $search['page'];
        }

        if(!isset($search['limit']) || $search['limit'] <= 0) {
            $limit = 100;
        } else {
            $limit = $search['limit'];
        }

        $query = $this->createQueryBuilder('e')->select('e');

        if (!empty($search['query'])) {
            $query->orWhere('c.firstName like :query')
                ->orWhere('c.lastName like :query')
                ->orWhere('c.jobTitle like :query')
                ->setParameter($query->expr()->like('query', $query['query']));
        }


        $paginator = new Paginator($query->getQuery());

        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1))
            ->setMaxResults($limit);

        return [
            'data' => $paginator->getQuery()->getResult(),
            'pagesCount' => (int) ceil($paginator->count() / $paginator->getQuery()->getMaxResults()),
            'totalItems' => (int) $paginator->count(),
        ];
    }
}
