<?php

namespace CoreBundle\Entity\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function search(array $param = [])
    {
        $query = $this->createQueryBuilder('e')->select('e');

        if (!empty($search['query'])) {
            $query->orWhere('c.firstName like :query')
                ->orWhere('c.lastName like :query')
                ->orWhere('c.jobTitle like :query')
                ->setParameter('query', '%' . $param['query'] . '%');
        }


        $paginator = new Paginator($query->getQuery());

        $paginator->getQuery()
            ->setFirstResult($param['limit'] * ($param['page'] - 1))
            ->setMaxResults($param['limit']);

        return [
            'data' => $paginator->getQuery()->getResult(),
            'pagesCount' => (int) ceil($paginator->count() / $paginator->getQuery()->getMaxResults()),
            'totalItems' => (int) $paginator->count(),
        ];
    }
}
