version: '2'
services:
    db:
        image: mysql
        ports:
            - 33006:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: digg
            MYSQL_USER: digg
            MYSQL_PASSWORD: digg
        restart:
          always
    nginx:
        build: ./nginx
        ports:
            - "8080:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
    elasticsearch:
      image: elasticsearch:1.7.5
      ports:
        - "9201:9200"
        - "9301:9300"
    php:
        build: ./php-fpm
        expose:
            - "9000"
        volumes:
            - ../:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
            - db
            - elasticsearch
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "82:80"
        links:
            - db
